spring.application.name=cabApp

#DB configuration
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create



#security config

jwt.secretKey = ${JWT_SECRET_KEY}


#smtp config
spring.mail.username=${MASTER_EMAIL_ID}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true